/**
 * Generates a cloud-init.yml file for deploying the stack to a VPS.
 * Compatible with Hetzner, DigitalOcean, Vultr, Linode, and any provider
 * that supports cloud-init user data.
 *
 * Based on the patterns from openclaw_docker-setup.sh and openclaw_install.sh:
 * 1. Installs Docker via the official convenience script
 * 2. Adds the default user to the docker group
 * 3. Verifies Docker Compose v2 plugin is available
 * 4. Creates /opt/openclaw/ with config, workspace, and identity directories
 * 5. Writes docker-compose.yml and .env inline (env with restrictive 0600 perms)
 * 6. Starts the stack with docker compose up -d
 * 7. Polls the gateway health endpoint until it responds (up to 120s)
 * 8. Logs all operations to /opt/openclaw/deploy.log
 */
export function generateCloudInit(options: {
	composeYaml: string;
	envContent: string;
	projectName: string;
	gatewayPort?: number;
}): string {
	const gatewayPort = options.gatewayPort ?? 18789;

	// Escape content for cloud-init write_files (indent by 8 spaces)
	const indentContent = (content: string) =>
		content
			.split("\n")
			.map((line) => `        ${line}`)
			.join("\n");

	return `#cloud-config
# Cloud-init for ${options.projectName}
# Generated by better-openclaw
# Compatible with: Hetzner, DigitalOcean, Vultr, Linode, AWS, GCP

package_update: true

packages:
  - curl
  - git
  - ca-certificates
  - gnupg

write_files:
  - path: /opt/openclaw/docker-compose.yml
    permissions: "0644"
    content: |
${indentContent(options.composeYaml)}

  - path: /opt/openclaw/.env
    permissions: "0600"
    content: |
${indentContent(options.envContent)}

  - path: /opt/openclaw/deploy.sh
    permissions: "0755"
    content: |
        #!/usr/bin/env bash
        # OpenClaw deployment script — runs as runcmd via cloud-init
        # All output logged to /opt/openclaw/deploy.log
        set -euo pipefail
        exec > >(tee -a /opt/openclaw/deploy.log) 2>&1
        echo "==> [$(date -u +%Y-%m-%dT%H:%M:%SZ)] Starting OpenClaw deployment"

        # Install Docker via official convenience script
        echo "==> Installing Docker"
        curl -fsSL https://get.docker.com | sh

        # Enable and start Docker daemon
        systemctl enable docker
        systemctl start docker

        # Add default user to docker group (cloud providers commonly use 'ubuntu' or 'root')
        DEFAULT_USER="\${SUDO_USER:-$(logname 2>/dev/null || echo root)}"
        if [ "$DEFAULT_USER" != "root" ]; then
          usermod -aG docker "$DEFAULT_USER"
          echo "==> Added $DEFAULT_USER to docker group"
        fi

        # Verify Docker Compose v2 plugin
        if ! docker compose version >/dev/null 2>&1; then
          echo "ERROR: Docker Compose v2 plugin not available" >&2
          exit 1
        fi
        echo "==> Docker Compose: $(docker compose version)"

        # Create openclaw directories (matching docker-setup.sh structure)
        # config: gateway config files (openclaw.json)
        # workspace: agent workspace and data
        # identity: device identity for Docker Desktop/Windows bind mount compat
        mkdir -p /opt/openclaw/openclaw/config
        mkdir -p /opt/openclaw/openclaw/workspace
        mkdir -p /opt/openclaw/openclaw/config/identity

        # Start the stack
        echo "==> Starting stack"
        cd /opt/openclaw
        docker compose up -d

        # Health check: poll gateway until it responds (up to 120 seconds)
        echo "==> Waiting for gateway health check on port ${gatewayPort}"
        RETRIES=60
        while [ "$RETRIES" -gt 0 ]; do
          if curl -sf "http://127.0.0.1:${gatewayPort}" >/dev/null 2>&1; then
            echo "==> Gateway is healthy"
            break
          fi
          RETRIES=$((RETRIES - 1))
          sleep 2
        done

        if [ "$RETRIES" -eq 0 ]; then
          echo "WARNING: Gateway did not respond within 120s. Check logs with:"
          echo "  docker compose -f /opt/openclaw/docker-compose.yml logs -f openclaw-gateway"
        fi

        # Print summary
        echo ""
        echo "==> Deployment complete at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "    Project: ${options.projectName}"
        echo "    Gateway: http://$(hostname -I | awk '{print $1}'):${gatewayPort}"
        echo ""
        echo "Useful commands:"
        echo "  docker compose -f /opt/openclaw/docker-compose.yml logs -f"
        echo "  docker compose -f /opt/openclaw/docker-compose.yml ps"
        echo "  docker compose -f /opt/openclaw/docker-compose.yml restart"
        echo ""
        echo "Channel setup (optional):"
        echo "  docker compose -f /opt/openclaw/docker-compose.yml run --rm openclaw-cli channels login"
        echo "  docker compose -f /opt/openclaw/docker-compose.yml run --rm openclaw-cli channels add --channel telegram --token <TOKEN>"

runcmd:
  - /opt/openclaw/deploy.sh

final_message: "OpenClaw stack '${options.projectName}' is ready! Connect to port ${gatewayPort}."
`;
}
