/**
 * Generates Grafana provisioning configuration files.
 *
 * Returns a map of file paths (relative to project root) to file contents.
 * Includes datasource provisioning YAML for the Prometheus connection.
 */
export function generateGrafanaConfig(): Record<string, string> {
	const files: Record<string, string> = {};

	// ── Datasource Provisioning ─────────────────────────────────────────────

	files["config/grafana/provisioning/datasources/prometheus.yml"] = `# ═══════════════════════════════════════════════════════════════════════════════
# Grafana Datasource Provisioning — Auto-generated by OpenClaw
# ═══════════════════════════════════════════════════════════════════════════════

apiVersion: 1

datasources:
  # Prometheus — primary metrics datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: ""
    version: 1
`;

	// ── Dashboard Provisioning ───────────────────────────────────────────────

	files["config/grafana/provisioning/dashboards/default.yml"] = `# ═══════════════════════════════════════════════════════════════════════════════
# Grafana Dashboard Provisioning — Auto-generated by OpenClaw
# ═══════════════════════════════════════════════════════════════════════════════

apiVersion: 1

providers:
  - name: "OpenClaw Dashboards"
    orgId: 1
    folder: "OpenClaw"
    type: file
    disableDeletion: false
    editable: true
    updateIntervalSeconds: 30
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: false
`;

	// ── Grafana Configuration (grafana.ini overrides) ────────────────────────

	files["config/grafana/grafana.ini"] = `# ═══════════════════════════════════════════════════════════════════════════════
# Grafana Configuration — Auto-generated by OpenClaw
# ═══════════════════════════════════════════════════════════════════════════════

[server]
root_url = %(protocol)s://%(domain)s/

[security]
# Admin credentials are set via environment variables:
#   GF_SECURITY_ADMIN_USER
#   GF_SECURITY_ADMIN_PASSWORD

[auth.anonymous]
enabled = false

[dashboards]
default_home_dashboard_path = /var/lib/grafana/dashboards/home.json

[alerting]
enabled = true

[unified_alerting]
enabled = true

[log]
mode = console
level = info
`;

	return files;
}
